import type { ArcTestnetSimulation, CircleRail, CircleRailPreview, Decision, PaymentPurpose } from "@/domain/payment-intent/types";
import type { SpendControls } from "@/domain/policy/spend-controls";

export type AuditRecord = {
  eventType: "agent_payment_guard_evaluated";
  auditId: string;
  timestamp: string;
  intentId?: string;
  idempotencyKey: string;
  agentId: string;
  intent: string;
  amount: string;
  amountUSDC?: string;
  currency: string;
  recipient: string;
  recipientId?: string;
  recipientLabel?: string;
  scenario: string;
  purpose?: PaymentPurpose;
  paymentRail: string;
  rail?: CircleRail;
  decision: Decision;
  riskScore: number;
  policyId: string;
  matchedRules: string[];
  reasonCodes: string[];
  reason: string;
  executionMode: CircleRailPreview["executionMode"];
  railPreview: CircleRailPreview;
  spendControls?: SpendControls;
  arcTestnetSimulation?: ArcTestnetSimulation;
};
