/**
 * I5 — stable Gateway-settlement reason codes (shared module).
 *
 * These codes are the security contract for the whole I5 surface: the I3
 * `remote_outcome_unknown` transition event, the settlement orchestration
 * results, and the operator gate all speak ONLY in these codes — never
 * free-form HTTP text, never raw error bodies.
 *
 * The module is dependency-free on purpose: `execution-store.ts` and
 * `gateway-settlement.ts` both import it, which avoids a circular import
 * (the store must validate transition reason codes without importing the
 * orchestrator that imports the store).
 */

export const X402_GATEWAY_READY = "X402_GATEWAY_READY" as const;
export const X402_GATEWAY_OPERATOR_AUTH_REQUIRED = "X402_GATEWAY_OPERATOR_AUTH_REQUIRED" as const;
export const X402_GATEWAY_EXECUTION_NOT_FOUND = "X402_GATEWAY_EXECUTION_NOT_FOUND" as const;
export const X402_GATEWAY_EXECUTION_NOT_SUBMITTED = "X402_GATEWAY_EXECUTION_NOT_SUBMITTED" as const;
export const X402_GATEWAY_AUTHORIZATION_EXPIRED = "X402_GATEWAY_AUTHORIZATION_EXPIRED" as const;
export const X402_GATEWAY_PAYLOAD_DIGEST_MISMATCH = "X402_GATEWAY_PAYLOAD_DIGEST_MISMATCH" as const;
export const X402_GATEWAY_REQUIREMENT_DIGEST_MISMATCH =
  "X402_GATEWAY_REQUIREMENT_DIGEST_MISMATCH" as const;
export const X402_GATEWAY_BINDING_MISMATCH = "X402_GATEWAY_BINDING_MISMATCH" as const;
export const X402_GATEWAY_RECOVERY_METADATA_MISSING = "X402_GATEWAY_RECOVERY_METADATA_MISSING" as const;
export const X402_GATEWAY_NETWORK_NOT_ALLOWED = "X402_GATEWAY_NETWORK_NOT_ALLOWED" as const;
export const X402_GATEWAY_TRANSPORT_TIMEOUT = "X402_GATEWAY_TRANSPORT_TIMEOUT" as const;
export const X402_GATEWAY_TRANSPORT_FAILURE = "X402_GATEWAY_TRANSPORT_FAILURE" as const;
export const X402_GATEWAY_RESPONSE_INVALID = "X402_GATEWAY_RESPONSE_INVALID" as const;
export const X402_GATEWAY_REMOTE_OUTCOME_UNKNOWN = "X402_GATEWAY_REMOTE_OUTCOME_UNKNOWN" as const;
export const X402_GATEWAY_KNOWN_REJECTION = "X402_GATEWAY_KNOWN_REJECTION" as const;
export const X402_GATEWAY_NONCE_ALREADY_USED_RECONCILE_REQUIRED =
  "X402_GATEWAY_NONCE_ALREADY_USED_RECONCILE_REQUIRED" as const;
export const X402_GATEWAY_REMOTE_TRANSFER_MISMATCH = "X402_GATEWAY_REMOTE_TRANSFER_MISMATCH" as const;
export const X402_GATEWAY_TRANSFER_PENDING = "X402_GATEWAY_TRANSFER_PENDING" as const;
export const X402_GATEWAY_TRANSFER_CONFIRMED = "X402_GATEWAY_TRANSFER_CONFIRMED" as const;
export const X402_GATEWAY_TRANSFER_FAILED = "X402_GATEWAY_TRANSFER_FAILED" as const;
export const X402_GATEWAY_SETTLEMENT_EVIDENCE_CONFLICT =
  "X402_GATEWAY_SETTLEMENT_EVIDENCE_CONFLICT" as const;
export const X402_GATEWAY_STATE_CONFLICT = "X402_GATEWAY_STATE_CONFLICT" as const;

export const X402_GATEWAY_REASON_CODES = [
  X402_GATEWAY_READY,
  X402_GATEWAY_OPERATOR_AUTH_REQUIRED,
  X402_GATEWAY_EXECUTION_NOT_FOUND,
  X402_GATEWAY_EXECUTION_NOT_SUBMITTED,
  X402_GATEWAY_AUTHORIZATION_EXPIRED,
  X402_GATEWAY_PAYLOAD_DIGEST_MISMATCH,
  X402_GATEWAY_REQUIREMENT_DIGEST_MISMATCH,
  X402_GATEWAY_BINDING_MISMATCH,
  X402_GATEWAY_RECOVERY_METADATA_MISSING,
  X402_GATEWAY_NETWORK_NOT_ALLOWED,
  X402_GATEWAY_TRANSPORT_TIMEOUT,
  X402_GATEWAY_TRANSPORT_FAILURE,
  X402_GATEWAY_RESPONSE_INVALID,
  X402_GATEWAY_REMOTE_OUTCOME_UNKNOWN,
  X402_GATEWAY_KNOWN_REJECTION,
  X402_GATEWAY_NONCE_ALREADY_USED_RECONCILE_REQUIRED,
  X402_GATEWAY_REMOTE_TRANSFER_MISMATCH,
  X402_GATEWAY_TRANSFER_PENDING,
  X402_GATEWAY_TRANSFER_CONFIRMED,
  X402_GATEWAY_TRANSFER_FAILED,
  X402_GATEWAY_SETTLEMENT_EVIDENCE_CONFLICT,
  X402_GATEWAY_STATE_CONFLICT
] as const;

export type X402GatewayReasonCode = (typeof X402_GATEWAY_REASON_CODES)[number];
